USE [CSC-CSD-S212_10407557]
GO

--DROP VIEW IF EXISTS [VIEW_ORDERS];
--CREATE VIEW [VIEW_ORDERS] AS
--SELECT *
--FROM OrderLine 
--JOIN [VIEW_STONES] AS vs
--ON vs.
--...
--...

SELECT * FROM StoneUnit;


--CREATE VIEW [VIEW_STONES]

--CREATE VIEW [VIEW_PERSONS]
--CREATE VIEW [VIEW_EMPLOYEES]
--CREATE VIEW [VIEW_SUPPLIERS]
--CREATE VIEW [VIEW_CUSTOMERS]

--CREATE VIEW [VIEW_MATERIALTYPES]

--CREATE VIEW [VIEW_LOCATIONCITY] AS
--SELECT StoreLocation.Name
--FROM StoreLocation
--LEFT JOIN City 
--ON StoreLocation.CityID = City.CityID
