DROP VIEW IF EXISTS VIEW_ORDERS
DROP VIEW IF EXISTS SelectAllStoneUnits
DROP VIEW IF EXISTS VIEW_PERSONS
DROP VIEW IF EXISTS VIEW_MATERIALTYPES
DROP VIEW IF EXISTS VIEW_SHAPES
DROP VIEW IF EXISTS VIEW_LOCATIONCITY
