USE [CSC-CSD-S212_10407562]
GO

DROP VIEW IF EXISTS VIEW_Persons
DROP VIEW IF EXISTS VIEW_MaterialTypes
DROP VIEW IF EXISTS VIEW_Shapes
DROP VIEW IF EXISTS VIEW_LocationCity
DROP VIEW IF EXISTS VIEW_SelectAllStoneUnits
DROP VIEW IF EXISTS VIEW_OrderProducts
DROP VIEW IF EXISTS VIEW_OrderInfo
